name 'chef_handler_example'
maintainer 'Greg Schofield'
maintainer_email 'greg.c.schofield@gmail.com'
license 'All Rights Reserved'
description 'And example of how to write chef handlers in 2021'
version '0.1.0'
chef_version '>= 15.0'
